# write your docker-compose code here.Use the `docker compose` command instead of the legacy `docker-compose`, as it is integrated into Docker CLI (v20.10+),eliminating the need for a separate binary. It provides better performance, consistency, and is actively maintained, unlike the legacy command.
version: '3.8'

networks:
  todo-netowrk:
    driver: bridge

volumes:
  mysql-data:

services:
  todo-application:
    image: todo-application-image:latest
    container_name: todo-application-pipeline-todo-application-1
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nuvelabs123$
    networks:
      - todo-network
    depeds_on:
      - mysql-db
  mysql-db:
    image: mysql:8
    container_name: todo-application-pipeline-mysql-db-1
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
      MYSQL_DATABASE: mysql-db
    ports:
      - "3307:3306"
    networs:
      - todo-network
    volumes:
      - mysql-data:/var/lib/mysql